### PR TITLE
Fix global query processing

### PR DESCRIPTION
**Pull request by shkarupa-alex**
Fixes https://github.com/NVlabs/GCVit/issues/10 , https://github.com/NVlabs/GCVit/issues/11 , https://github.com/NVlabs/GCVit/issues/13

### CODE REVIEW

**Comment by ahatamiz** [comment]
@shkarupa-alex thanks for the great comments reflected in this PR. We will review and address if needed.

**Comment by pamolchanov** [comment]
Hi @shkarupa-alex, thank you for looking in to the code and providing a fix for the issue you found. We appreciate it a lot. Let us review and confirm changes before accepting PR. We will be back to this issue the next week.

**Comment by awsaf49** [comment]
@shkarupa-alex  I think `repeat` + `reshape` can be replaced with one `repeat_interleave` op as `torch.Tensor.repeat => np.tile` whereas `torch.repeat_interleave => np.repeat`,
before,
```py
q_global = q_global.reshape(B, 1, N, self.num_heads, C // self.num_heads).permute(0, 1, 3, 2, 4)
q = q_global.repeat(1, B_//B, 1, 1, 1).reshape(B_, self.num_heads, N, C // self.num_heads)
```
after,
```py
q_global = q_global.reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
q = torch.repeat_interleave(q_global, repeats=B_//B, dim=0)
```

**Comment by ahatamiz** [comment]
Hi @shkarupa-alex and @awsaf49 

We have updated our models and re-trained them. In all cases, the accuracy is better compared to reported numbers in the paper, from our internal checkpoints. In this version, we have converted tensors to be in nhwc dimensions, and only be bchw for conv layers. In addition, we have conducted a set of stress tests and verified there is no inconsistency with the model performance across different batch sizes at test time. The new version of the model shows improvement of 0.15 on average over the previous model across all 5 variants. We would like to thank @rwightman , @shkarupa-alex and @awsaf49 for pointing out the issues with the initial release.

Best,

**Pull request closed without merging**
